nelmio_api_doc:
    documentation:
        info:
            title: Пример приложения на Symfony 5.2.
            description: API для книг и авторов.
            version: 1.0.0
        components:
            schemas:
                Book:
                    description: Книга.
                    type: object
                    required:
                        - name
                    properties:
                        id:
                            title: Идентификатор книги
                            type: integer
                            example: 42
                        name:
                            title: Название книги
                            type: string
                            example: Война и мир
                        authors:
                            title: Авторы
                            type: array
                            items:
                                $ref: "#/components/schemas/Author"
                LocalizedBook:
                    description: Объект книги на нескольких языках.
                    type: object
                    properties:
                        ru:
                            title: Книга на русском языке
                            type: object
                            $ref: "#/components/schemas/Book"
                        en:
                            title: Книга на английском языке
                            type: object
                            $ref: "#/components/schemas/Book"
                Author:
                    description: Автор.
                    type: object
                    required:
                        - name
                    properties:
                        id:
                            title: Идентификатор автора
                            type: integer
                            example: 42
                        name:
                            title: Имя автора
                            type: string
                            example: Иванов Иван
                SuccessAddBook:
                    description: Успешное добавление книги.
                    type: object
                    required:
                        - bookId
                    properties:
                        bookId:
                            title: Идентификатор книги
                            type: integer
                            example: 42

                Error:
                    description: Ошибка.
                    type: object
                    required:
                        - message
                    properties:
                        message:
                            title: Описание ошибки
                            type: string
                            example: Books not found
    areas:
        path_patterns:
            - ^/api/doc.json$
            - /book
