nelmio_api_doc:
    documentation:
        info:
            title: Symfony example App.
            description: API for authors and books.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/doc.json$
